# # For creating a project in AlianHub and deleting it after completion of the flow
# import re
# from playwright.sync_api import Playwright, sync_playwright, expect


# def run(playwright: Playwright) -> None:
#     browser = playwright.chromium.launch(headless=False)
#     context = browser.new_context(viewport={"width":1920,"height":1028})
#     page = context.new_page()
#     page.goto("http://localhost:4000/#/login?redirect_url=/67b448c342af43e63b38fda6/project/6834207579b2ebd7f9a2ba06/p?tab=ProjectListView")
#     page.get_by_role("textbox", name="Email ID*").click()
#     page.get_by_role("textbox", name="Email ID*").fill("riap1330+999@gmail.com")
#     page.get_by_role("textbox", name="Password*").click()
#     page.get_by_role("textbox", name="Password*").fill("VimalSir@223133")
#     page.locator("form").get_by_role("img").click()
#     page.locator("label").filter(has_text="Remember Me").click()
#     page.get_by_role("button", name="Login").click()
#     page.get_by_role("button", name="No").click()
#     page.get_by_role("button", name="+ New Project").click()
#     page.locator("#createprojectusingtemplate_driver").get_by_role("button").click()
#     page.locator(".template_project_img > .cursor-pointer").first.click()
#     page.get_by_role("button", name="Use Template").click()
#     page.get_by_role("textbox", name="Enter Project Name").click()
#     page.get_by_role("textbox", name="Enter Project Name").fill("Mission 44")
#     page.get_by_role("textbox", name="Enter Key Name").click()
#     page.get_by_role("textbox", name="Enter Key Name").fill("LH44")
#     page.get_by_role("textbox", name="Select Category").click()
#     page.locator("#item2").click()
#     page.locator("[data-test-id=\"dp-input\"]").click()
#     page.locator("[data-test-id=\"Sat May 31 2025 00\\:00\\:00 GMT\\+0530 \\(India Standard Time\\)\"]").get_by_text("31").click()
#     page.get_by_role("img", name="add user").click()
#     page.get_by_text("Dipam Shah").click()
#     page.get_by_role("img", name="closeButton").click()
#     page.locator("li:nth-child(13)").click()
#     page.get_by_role("button", name="Create Project").click()
#     page.get_by_text("View", exact=True).click()
#     page.locator("div").filter(has_text=re.compile(r"^Activity$")).nth(1).click()
#     page.get_by_role("button", name="Add View").click()
#     page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
#     page.locator("div").filter(has_text=re.compile(r"^Delete$")).nth(1).click()
#     page.get_by_role("textbox", name="delete").fill("delete")
#     page.get_by_role("button", name="Delete").click()

#     # ---------------------
#     context.close()
#     browser.close()


# with sync_playwright() as playwright:
#     run(playwright)



import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(viewport={"width":1900,"height":1000})
    page = context.new_page()
    page.goto("http://localhost:4000/#/login?redirect_url=/67b448c342af43e63b38fda6/project/6834207579b2ebd7f9a2ba06/p?tab=ProjectListView")
    page.get_by_role("textbox", name="Email ID*").click()
    page.get_by_role("textbox", name="Email ID*").fill("riap1330+999@gmail.com")
    page.get_by_role("textbox", name="Password*").click()
    page.get_by_role("textbox", name="Password*").fill("VimalSir@223133")
    page.locator("form").get_by_role("img").click()
    page.get_by_text("Remember Me").click()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="No").click()
    page.get_by_role("button", name="+ New Project").click()
    page.locator("#createblankproject_driver").get_by_role("button").click()
    page.get_by_role("textbox", name="Enter Project Name").click()
    page.get_by_role("textbox", name="Enter Project Name").fill("Dipam Shah")
    page.get_by_role("textbox", name="Enter Project Name").press("Tab")
    page.get_by_role("textbox", name="Enter Key Name").press("ArrowRight")
    page.get_by_role("textbox", name="Enter Key Name").fill("DSa")
    page.get_by_role("textbox", name="Select Category").click()
    page.locator("#item1").click()
    page.locator("[data-test-id=\"dp-input\"]").click()
    page.locator("[data-test-id=\"Sat May 31 2025 00\\:00\\:00 GMT\\+0530 \\(India Standard Time\\)\"]").get_by_text("31").click()
    page.locator("#createprojectleadassignee_driver").get_by_role("img", name="add user").click()
    page.get_by_text("Dipam Shah").click()
    page.get_by_role("img", name="closeButton").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).click()
    page.locator("li:nth-child(13)").click()
    page.get_by_text("Upload").click()
    page.get_by_text("PreviousNext").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="+ Add Status").click()
    page.locator("div").filter(has_text=re.compile(r"^Backlog$")).first.click()
    page.locator("div").filter(has_text=re.compile(r"^Complete$")).nth(2).click()
    page.get_by_text("Complete").nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Awaiting Feedback$")).first.click()
    page.locator("div").filter(has_text=re.compile(r"^Deferred$")).first.click()
    page.locator("div").filter(has_text=re.compile(r"^Code Review$")).first.click()
    page.locator("div").filter(has_text=re.compile(r"^\+ Add Status$")).get_by_role("img").click()
    page.get_by_role("button", name="Next").click()
    page.locator("div").filter(has_text=re.compile(r"^Turn off all Apps$")).locator("div").nth(1).click()
    page.get_by_role("button", name="Next").click()
    page.locator("div:nth-child(5) > .text-toggle > .toggle").click()
    page.locator(".outline-required > .text-toggle > .toggle").first.click()
    page.locator("div:nth-child(6) > .text-toggle > .toggle").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Create Project").click()
    page.get_by_role("img", name="dots", exact=True).click()
    page.get_by_text("Create New Sprint").click()
    page.get_by_role("textbox", name="Enter sprint name").fill("fsfaggda")
    page.get_by_role("textbox", name="Enter sprint name").press("Enter")
    page.get_by_role("img", name="dots", exact=True).click()
    page.locator("#my-dropdown div").filter(has_text="Create New Folder").nth(3).click()
    page.get_by_role("textbox", name="Enter directory name").fill("gsgsaghe")
    page.get_by_role("textbox", name="Enter directory name").press("Enter")
    page.locator("#project_sidebar_container div").filter(has_text=re.compile(r"^Dipam Shah$")).locator("div").first.click()
    page.get_by_text("Rename").click()
    page.get_by_role("textbox", name="Project Name").fill("Dipam Shahfgvdsg")
    page.get_by_role("textbox", name="Project Name").press("Enter")
    page.get_by_role("img", name="dots", exact=True).click()
    page.get_by_text("Color & Avatar").click()
    page.locator("li:nth-child(20)").click()
    page.get_by_role("button", name="Save").click()
    page.locator("#project_sidebar_container div").filter(has_text=re.compile(r"^Dipam Shahfgvdsg$")).locator("div").first.click()
    page.get_by_text("Close Project").click()
    page.get_by_role("textbox", name="close").click()
    page.get_by_role("textbox", name="close").fill("close")
    page.get_by_role("textbox", name="close").press("Tab")
    page.get_by_role("button", name="Cancel").press("Tab")
    page.get_by_role("button", name="Close").press("Enter")
    page.get_by_role("button", name="Close").press("Enter")
    page.get_by_role("button", name="Close").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
