# This code is generated by Playwright Codegen

import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.saucedemo.com/")
    page.pause()

    # page.locator("[data-test=\"login-credentials\"]").click()
    # page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standard_user")
    # page.locator("[data-test=\"username\"]").press("Tab")
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    page.locator("[data-test=\"login-button\"]").click()

# Some of the commands that I used to generate the code using Playwright Codegen:
# PS C:\Users\Alian-172\Desktop\PlayWright> playwright codegen --device="iPhone 13" https://www.saucedemo.com/
# PS C:\Users\Alian-172\Desktop\PlayWright> playwright codegen --viewport-size=800,600 saucedemo.py 
# PS C:\Users\Alian-172\Desktop\PlayWright> playwright codegen --viewport-size=800,600 https://www.saucedemo.com/
# PS C:\Users\Alian-172\Desktop\PlayWright> playwright codegen --color-scheme=dark https://x.com/
# PS C:\Users\Alian-172\Desktop\PlayWright> playwright codegen --timezone="Europe/Rome" --geolocation="41.890221,12.492348" --lang="it-IT" bing.com/maps


# Page to refer: https://playwright.dev/python/docs/codegen

# Can use some tools for debuggind and inspecting in the browser console:
#Some cmnds to use in the browser console:
# playwright.inspect('input')
# playwright.$$('input')